# Source: acme/templates/cert-manager-prod-clusterissuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    meta.helm.sh/release-name: 'acme-jx'
  labels:
    gitops.jenkins-x.io/pipeline: 'cluster'
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "k.gocheva@blubito.com"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - selector:
          dnsNames:
            - "*.blubitoapps.com"
            - "blubitoapps.com"
        # ACME DNS-01 provider configurations
        dns01:
          route53:
            region: eu-central-1
